### ISSUE TITLE
Cleaning all kernels has broken

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-agent#115]
This happens when trying to stop/restart the agent as a systemd service with SIGTERM. 
```
7월 10 23:17:38 node01 systemd[1]: Stopping Backend.AI Agent...
 7월 10 23:17:38 node01 run-agent.sh[43447]: 2019-07-10 23:17:38 INFO ai.backend.agent.server [43447] shutting down...
 7월 10 23:17:38 node01 run-agent.sh[43447]: 2019-07-10 23:17:38 INFO ai.backend.agent.server [43447] cleaning all kernels...
 7월 10 23:17:38 node01 run-agent.sh[43447]: 2019-07-10 23:17:38 ERROR ai.backend.agent.server [43447] _destroy_kernel(c1569ce3-0a07-46fb-bd64-1997d849c805) operation cancelled
 7월 10 23:17:38 node01 run-agent.sh[43447]: Traceback (most recent call last):
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/backend.ai/agent/src/ai/backend/agent/server.py", line 1307, in _destroy_kernel
 7월 10 23:17:38 node01 run-agent.sh[43447]:     await self.stat_sync_states[cid].terminated.wait()
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/.pyenv/versions/3.6.8/lib/python3.6/asyncio/locks.py", line 283, in wait
 7월 10 23:17:38 node01 run-agent.sh[43447]:     yield from fut
 7월 10 23:17:38 node01 run-agent.sh[43447]: concurrent.futures._base.CancelledError
 7월 10 23:17:38 node01 run-agent.sh[43447]: 2019-07-10 23:17:38 ERROR ai.backend.agent.server [43447] _destroy_kernel(fd61290f-599b-4d7d-84fb-fcf10d0c31a2) operation cancelled
 7월 10 23:17:38 node01 run-agent.sh[43447]: Traceback (most recent call last):
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/backend.ai/agent/src/ai/backend/agent/server.py", line 1307, in _destroy_kernel
 7월 10 23:17:38 node01 run-agent.sh[43447]:     await self.stat_sync_states[cid].terminated.wait()
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/.pyenv/versions/3.6.8/lib/python3.6/asyncio/locks.py", line 283, in wait
 7월 10 23:17:38 node01 run-agent.sh[43447]:     yield from fut
 7월 10 23:17:38 node01 run-agent.sh[43447]: concurrent.futures._base.CancelledError
 7월 10 23:17:38 node01 run-agent.sh[43447]: Exception in thread Thread-1:
 7월 10 23:17:38 node01 run-agent.sh[43447]: Traceback (most recent call last):
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
 7월 10 23:17:38 node01 run-agent.sh[43447]:     self.run()
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
 7월 10 23:17:38 node01 run-agent.sh[43447]:     self._target(*self._args, **self._kwargs)
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/.pyenv/versions/venv-kxp5drow-agent/lib/python3.6/site-packages/aiotools/server.py", line 271, in _worker_main
 7월 10 23:17:38 node01 run-agent.sh[43447]:     loop.run_until_complete(ctx.__aexit__(None, None, None))
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "uvloop/loop.pyx", line 1446, in uvloop.loop.Loop.run_until_complete
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/.pyenv/versions/venv-kxp5drow-agent/lib/python3.6/site-packages/aiotools/server.py", line 103, in __aexit__
 7월 10 23:17:38 node01 run-agent.sh[43447]:     await self._agen.asend(self.yield_return)
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/backend.ai/agent/src/ai/backend/agent/server.py", line 1819, in server_main
 7월 10 23:17:38 node01 run-agent.sh[43447]:     await agent.shutdown(stop_signal)
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/backend.ai/agent/src/ai/backend/agent/server.py", line 587, in shutdown
 7월 10 23:17:38 node01 run-agent.sh[43447]:     await self.stat_sync_task
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/backend.ai/agent/src/ai/backend/agent/server.py", line 445, in sync_container_stats
 7월 10 23:17:38 node01 run-agent.sh[43447]:     cstat = await asyncio.shield(self.stat_ctx.collect_container_stat(cid))
 7월 10 23:17:38 node01 run-agent.sh[43447]:   File "/home/devops/backend.ai/agent/src/ai/backend/agent/stats.py", line 421, in collect_container_stat
 7월 10 23:17:38 node01 run-agent.sh[43447]:     kernel_id = kernel_id_map[cid]
 7월 10 23:17:38 node01 run-agent.sh[43447]: KeyError: 'af96ab3ab3c3cfd0f4afc927ad32a5443c3cf89094bf8b1146e4f8700699b1aa'
 7월 10 23:17:38 node01 run-agent.sh[43447]: 2019-07-10 23:17:38 INFO ai.backend.agent.server [43447] exit.
 7월 10 23:17:38 node01 run-agent.sh[43447]: 2019-07-10 23:17:38 ERROR asyncio [43447] Task was destroyed but it is pending!
 7월 10 23:17:38 node01 run-agent.sh[43447]: task: <Task pending coro=<AgentRPCServer.handle_agent_socket() running at /home/devops/backend.ai/agent/src/ai/backend/agent/server.py:629> wait_for=<Future pending cb=[_AsyncSocket._add_recv_event.<locals>.<lambda>() at /home/devops/.pyenv/versions/venv-kxp5drow-agent/lib/python3.6/site-packages/zmq/_future.py:329, <TaskWakeupMethWrapper object at 0x7f62a903ab88>()]>>
 7월 10 23:17:38 node01 run-agent.sh[43447]: 2019-07-10 23:17:38 ERROR asyncio [43447] Task was destroyed but it is pending!
 7월 10 23:17:38 node01 run-agent.sh[43447]: task: <Task pending coro=<RedisConnection._read_data() running at /home/devops/.pyenv/versions/venv-kxp5drow-agent/lib/python3.6/site-packages/aioredis/connection.py:183> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f62a8f8f7c8>()]> cb=[Future.set_result()]>
```

**Comment by achimnol** [comment]
In the agent v19.09.0b8, we have refactored and rewritten kernel cleanups, and SIGINT/SIGTERM termination works better.
