### ISSUE TITLE
Uploading file fails when creating a session with file to be executed

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-agent#137]
It seems like `DockerKernel` object does not have `config` attribute, but [this line](https://github.com/lablup/backend.ai-agent/blob/master/src/ai/backend/agent/docker/kernel.py#L92) tries to reference it.

Environment: latest master (https://github.com/lablup/backend.ai-agent/commit/eb114fd36b8398bbf869aa5d5271e7fc3abe7ece)
Steps to reproduce:
* Run `backend.ai run python:3.6-ubuntu18.04 main.py`, where main.py is any python code.
* Container is created, but there is an error when uploading `main.py`.
* Agent's traceback:
```
019-08-31 19:09:10 INFO ai.backend.gateway.kernel [74180] UPLOAD_FILE (u:AKIAIOSFODNN7EXAMPLE/AKIAIOSFODNN7EXAMPLE, token:d50c002bde)
2019-08-31 19:09:10 ERROR ai.backend.gateway.kernel [74180] UPLOAD_FILES: exception
Traceback (most recent call last):
  File "/Users/adrysn/Develop/backend.ai/backend.ai-dev/manager/src/ai/backend/gateway/kernel.py", line 599, in upload_files
    await asyncio.gather(*upload_tasks)
  File "/Users/adrysn/Develop/backend.ai/backend.ai-dev/manager/src/ai/backend/manager/registry.py", line 965, in upload_file
    return await coro
  File "/Users/adrysn/.pyenv/versions/manager/lib/python3.6/site-packages/aiotools/context.py", line 115, in __aexit__
    await self._agen.athrow(exc_type, exc_value, tb)
  File "/Users/adrysn/Develop/backend.ai/backend.ai-dev/manager/src/ai/backend/manager/registry.py", line 193, in handle_kernel_exception
    raise exc_class('FAILURE', e) from None
ai.backend.gateway.exceptions.KernelExecutionFailed: 500 Internal Server Error
-> Agent-side error: AttributeError("'DockerKernel' object has no attribute 'config'")
```

**Comment by achimnol** [comment]
Now fixed.
