### ISSUE TITLE
Accumulation of docker destroy errors

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai-agent#46]
Below cases seem to affect accumulation of docker container destroy errors.

```
2017-10-19 16:27:32 ERROR sorna.agent.kernel unexpected error
Traceback (most recent call last):
  File "/home/devops/venv/lib/python3.6/site-packages/sorna/agent/kernel.py", line 276, in read_output
    decoders[0].decode(msg_data),
  File "/home/devops/.pyenv/versions/3.6.2/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 0: invalid continuation byte
2017-10-19 16:27:45 WARNING sorna.agent.server _destroy_kernel(83KfJyAm256_qHJf8RHR1g) interrupting running execution
2017-10-19 16:27:47 WARNING sorna.agent.server _destroy_kernel(8vXsMfiIvTBThG7GIvqONw) interrupting running execution
2017-10-19 16:27:53 ERROR sorna.agent.kernel unexpected error
Traceback (most recent call last):
  File "/home/devops/venv/lib/python3.6/site-packages/sorna/agent/kernel.py", line 276, in read_output
    decoders[0].decode(msg_data),
  File "/home/devops/.pyenv/versions/3.6.2/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 0: invalid continuation byte
2017-10-19 16:27:57 INFO sorna.agent.server restarting docker.events.run()
2017-10-19 16:30:13 WARNING sorna.agent.server _destroy_kernel(R0iMoQfQnGiz5cZQljzDvg) interrupting running execution
2017-10-19 16:30:13 ERROR sorna.agent.kernel unexpected error
Traceback (most recent call last):
  File "/home/devops/venv/lib/python3.6/site-packages/sorna/agent/kernel.py", line 201, in get_next_result
    rec = await self.console_queue.get()
  File "/home/devops/.pyenv/versions/3.6.2/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError
```

```
2017-10-23 11:51:35 ERROR sorna.agent.server unexpected error
Traceback (most recent call last):
  File "/home/devops/venv/lib/python3.6/site-packages/aiodocker/events.py", line 54, in run
    async for data in self.json_stream:
  File "/home/devops/venv/lib/python3.6/site-packages/aiodocker/jsonstream.py", line 26, in __anext__
    data = yield from self._response.content.readline()
  File "/home/devops/venv/lib/python3.6/site-packages/aiohttp/streams.py", line 570, in readline
    return (yield from super().readline())
  File "/home/devops/venv/lib/python3.6/site-packages/aiohttp/streams.py", line 268, in readline
    yield from self._wait('readline')
  File "/home/devops/venv/lib/python3.6/site-packages/aiohttp/streams.py", line 235, in _wait
    yield from waiter
  File "/home/devops/venv/lib/python3.6/site-packages/aiohttp/helpers.py", line 743, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devops/venv/lib/python3.6/site-packages/sorna/agent/server.py", line 585, in fetch_docker_events
    await self.docker.events.run()
  File "/home/devops/venv/lib/python3.6/site-packages/aiodocker/events.py", line 57, in run
    await self.json_stream._close()
AttributeError: 'NoneType' object has no attribute '_close'
```

**Comment by achimnol** [comment]
The second case is patched in aiodocker, but not released yet.
We need to install the master version until then.

**Comment by achimnol** [comment]
Hot-fixed the master branch and the production server not to raise exceptions with decoding errors but replace errorneous characters with `'\ufffd'`. C-language users often seem to generate non-UTF8 characters...

**Comment by achimnol** [comment]
And, CancelledError in `get_next_result()` is already fixed in the master branch as well while handling #41.

**Comment by achimnol** [comment]
Now applied hot-fixes to all agent instances. I will release a new version of aiodocker this weekend.
